import { FileHelper, z } from '@start9labs/start-sdk'
import { sdk } from '../sdk'

/**
 * StartOS-side state for this package. Deliberately separate from GitLab's own
 * configuration: `/etc/gitlab/gitlab.rb` is generated by Omnibus and must
 * contain only keys Omnibus recognises, so choices that belong to StartOS live
 * here instead.
 */
const shape = z
  .object({
    /**
     * The address GitLab treats as canonical — baked into clone URLs, generated
     * links and emails. Chosen by the user from the addresses StartOS exposes
     * (LAN / Tor / clearnet); seeded to the .local address at install.
     */
    primaryUrl: z.string().catch(''),

    /**
     * Generated at install and shown to the user once. Kept so the Initial
     * Credentials action can re-display it; cleared when the user rotates the
     * password, since it is no longer the truth at that point.
     */
    initialRootPassword: z.string().catch(''),

    /**
     * Set after the initial-credentials task has been raised, so a restart does
     * not re-raise it every time main runs.
     */
    rootPasswordAcknowledged: z.boolean().catch(false),

    /**
     * Admin API token the package mints for its own use, re-issued on every
     * start. Actions use it instead of booting Rails in a throwaway container,
     * which cannot work: reconfigure writes Rails' config into the image layer,
     * not onto a volume.
     */
    internalToken: z.string().catch(''),

    /** SMTP selection, in the shape the SDK's smtp input spec produces. */
    smtp: z
      .object({
        selection: z.string().catch('disabled'),
        value: z.record(z.string(), z.unknown()).catch({}),
      })
      .catch({ selection: 'disabled', value: {} }),
  })
  .strip()

export const storeJson = FileHelper.json(
  { base: sdk.volumes.main, subpath: './store.json' },
  shape,
)
